---
name: Library-CallNumber-LC
version: 0.10
author:
  - 'Bill Dueber <dueberb@umich.edu>'
abstract: Deal with Library-of-Congress call numbers
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Math::BigInt: 0
build_requires:
  Math::BigInt: 0
  Test::More: 0
provides:
  Library::CallNumber::LC:
    file: lib/Library/CallNumber/LC.pm
    version: 0.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
